baseURL = '/'
languageCode = 'zh-cn'
title = '海海杂说'
theme = "@zsea"
copyright = "© Copyright 2025. All rights reserved."
enableRobotsTXT = true
timeZone = "Asia/Shanghai"
googleAnalytics = "G-CD1V6LJ8FT"
[params]
icons = "https://at.alicdn.com/t/c/font_5020669_vahvl9zr1gq.css"
avatar = "/favicon/logo.png"
name = "海海"
desc = "软件开发初学者，爱好者。"
icp = "蜀ICP备2023031169号-1"
logo = "/favicon/logo.png"
favicon = "/favicon/favicon-32x32.png"

description = "个人博客，计算机技术，软件开发，编码转换，JSON工具，JSON格式化，JSON比较"
keywords = "个人博客，计算机技术，软件开发，编码转换，JSON工具，JSON格式化，JSON比较"

[pagination]
pagerSize  = 10

[permalinks]
    posts = "/posts/:slug/"
    products = "/products/:slug/"

[[menus.main]]
name = '首页'
pageRef = '/'
weight = 10
[menus.main.params]
icon = 'icon-home'

[[menus.main]]
name = '博客'
pageRef = '/posts'
weight = 20
[menus.main.params]
icon = 'icon-medium'

[[menus.main]]
name = '产品'
pageRef = '/products'
weight = 30
[menus.main.params]
icon = 'icon-chanpin'

[[menus.main]]
name = '动态'
pageRef = '/moments'
weight = 40
[menus.main.params]
icon = 'icon-shejiaotubiao-02'

[[menus.main]]
name = '关于'
pageRef = '/about'
weight = 50
[menus.main.params]
icon = 'icon-guanyuwomen'

[[menus.tools]]
name = '编码转换'
url = 'http://web.chacuo.net/charsetdatauri'
weight = 1
[menus.tools.params]
icon = 'icon-xml'

[[menus.tools]]
name = 'JSON编辑器'
url = '/json'
weight = 2
[menus.tools.params]
icon = 'icon-json'

[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1

[services]
  [services.googleAnalytics]
    googleAnalytics = 'G-CD1V6LJ8FT'